version: '3'

services:
  awsm:
    image: awsm
    build: ./
    container_name: awsm
    network_mode: host
    volumes:
        - ./work:/work
        - ~/.ssh:/home/work/.ssh
        - ~/.aws:/home/work/.aws
        - ./home/.local:/home/work/.local
        - ./home/.boto:/home/work/.boto
        - ./home/.vimrc:/home/work/.vimrc
        - ./home/.bashrc:/home/work/.bashrc
        - ./home/.mybashrc:/home/work/.mybashrc
    privileged: true
